function [BoundingBox,Left,Top,Right,Bottom] = import_txt(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [BOUNDINGBOX,LEFT,VARNAME3,TOP,VARNAME5,RIGHT,VARNAME7,BOTTOM,VARNAME9]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [BOUNDINGBOX,LEFT,VARNAME3,TOP,VARNAME5,RIGHT,VARNAME7,BOTTOM,VARNAME9]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [BoundingBox,Left,VarName3,Top,VarName5,Right,VarName7,Bottom,VarName9] = importfile('twomice1.txt',1, 99563);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/08/07 17:47:21
% Author: Ahmet Arac, Department of Neurology, UCLA, Los Angeles, CA

%% Initialize variables.
delimiter = {',','=',':'};
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format for each line of text:
%   column1: text (%q)
%	column2: text (%q)
%   column3: double (%f)
%	column4: text (%q)
%   column5: double (%f)
%	column6: text (%q)
%   column7: double (%f)
%	column8: text (%q)
%   column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%f%q%f%q%f%q%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'WhiteSpace', '', 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
BoundingBox = dataArray{:, 1};
Left = dataArray{:, 3};
% VarName3 = dataArray{:, 3};
Top = dataArray{:, 5};
% VarName5 = dataArray{:, 5};
Right = dataArray{:, 7};
% VarName7 = dataArray{:, 7};
Bottom = dataArray{:, 9};
% VarName9 = dataArray{:, 9};


